### ISSUE TITLE
Is.number missing union with null

### ISSUE THREAD

**Issue by Honga1** [dec-land/as-is#1]
Hey :) I saw your lib on reddit. I was just reading the source and saw this:

https://github.com/dec-land/as-is/blob/c35e237991f38cd2d086f01f0c81f42d38d7fb11/is/index.ts#L18

Shouldn't you return `number | null` if it is allowed to be null?

**Comment by dec-land** [comment]
You're right! I'll actually remove the allowNull checks, they were specific to my project in which I was filtering out properties from an object unless they were the correct type.  But if they were null I wanted them to remain. 

I should really enable strict mode too in the tsconfig which would have reported a warning here, it was disabled in the legacy projects i've been working on which I created as-is for. Good spot 👍

**Comment by dec-land** [comment]
Issue closed, allowNull has been removed as stated above. Ty :)
